# Generated by Django 2.0.7 on 2020-09-01 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='pretty_picture1',
            field=models.ImageField(default=2, upload_to=''),
            preserve_default=False,
        ),
    ]
