# Generated by Django 2.0.7 on 2020-09-01 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0002_destination_pretty_picture1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='pretty_picture1',
        ),
    ]
