# Generated by Django 2.0.7 on 2020-09-02 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0004_auto_20200902_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='pretty_picture2',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='destination',
            name='pretty_picture3',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
